name: Deploy to GithubPages

on:
  pull_request:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: src
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true


