name: Deploy to GithubPages

on:
  pull_request:
    branches:
      -main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
            folder: src
            target-folder: .
            branch: gh-pages
            clean: true


